// ═══════════════════════════════════════════════════════════════════════════
//  完整渲染格式 — 由 menu-raw.js 展開，含四語言翻譯
//  請勿手動編輯此檔，如需更改品項請編輯 menu-raw.js
// ═══════════════════════════════════════════════════════════════════════════

var menuCategories = {
  noodle_soup: { zh: '湯麵類', en: 'Noodle Soups',  ja: 'スープ麺',    ko: '쌀국수류' },
  stir_fry:    { zh: '炒類',   en: 'Stir-fry',       ja: '炒め物',      ko: '볶음류'   },
  dry:         { zh: '乾類',   en: 'Dry Dishes',     ja: '乾麺・ご飯',  ko: '건식류'   },
  soup:        { zh: '湯',     en: 'Soups',          ja: 'スープ',      ko: '수프'     },
  drink:       { zh: '飲料',   en: 'Drinks',         ja: 'ドリンク',    ko: '음료'     },
  dessert:     { zh: '甜點',   en: 'Desserts',       ja: 'デザート',    ko: '디저트'   },
};

var menuItems = [
  // ════════════════════════════════════════════════════════
  //  湯麵類 NOODLE SOUPS
  // ════════════════════════════════════════════════════════
  {
    id: 'noodle_soup-001', category: 'noodle_soup',
    names: { zh: '鮮蔬米線', en: 'Fresh Vegetable Rice Noodle Soup', ja: '野菜ビーフンスープ', ko: '신선 채소 쌀국수' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-002', category: 'noodle_soup',
    names: { zh: '鮮蔬空心麵', en: 'Fresh Vegetable Macaroni Soup', ja: '野菜マカロニスープ', ko: '신선 채소 마카로니 수프' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-003', category: 'noodle_soup',
    names: { zh: '鮮蔬米苔目', en: 'Fresh Vegetable Rice Cake Noodle Soup', ja: '野菜ライスケーキ麺スープ', ko: '신선 채소 쌀떡 국수' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-004', category: 'noodle_soup',
    names: { zh: '鮮蔬冬粉', en: 'Fresh Vegetable Glass Noodle Soup', ja: '野菜春雨スープ', ko: '신선 채소 당면 수프' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-005', category: 'noodle_soup',
    names: { zh: '紅燒河粉', en: 'Braised Flat Rice Noodle Soup', ja: '醤油ブレイズドフォー', ko: '홍소 쌀 납작면 수프' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-006', category: 'noodle_soup',
    names: { zh: '紅燒素米線', en: 'Braised Vegetarian Rice Noodle Soup', ja: '醤油ブレイズドビーフン', ko: '홍소 채식 쌀국수' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-007', category: 'noodle_soup',
    names: { zh: '紅燒麵', en: 'Braised Noodle Soup', ja: '醤油ブレイズド麺スープ', ko: '홍소 면 수프' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-008', category: 'noodle_soup',
    names: { zh: '紅燒冬粉', en: 'Braised Glass Noodle Soup', ja: '醤油ブレイズド春雨スープ', ko: '홍소 당면 수프' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-009', category: 'noodle_soup',
    names: { zh: '番茄米線', en: 'Tomato Rice Noodle Soup', ja: 'トマトビーフンスープ', ko: '토마토 쌀국수' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'noodle_soup-010', category: 'noodle_soup',
    names: { zh: '筍子米線', en: 'Bamboo Shoot Rice Noodle Soup', ja: 'タケノコビーフンスープ', ko: '죽순 쌀국수' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍜', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '季節限定', en: 'Seasonal item', ja: '季節限定', ko: '계절 한정' },
  },

  // ════════════════════════════════════════════════════════
  //  炒類 STIR-FRY
  // ════════════════════════════════════════════════════════
  {
    id: 'stir_fry-001', category: 'stir_fry',
    names: { zh: '越式炒河粉', en: 'Vietnamese Stir-fried Flat Rice Noodle', ja: 'ベトナム風炒めフォー', ko: '베트남식 볶음 쌀 납작면' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🥢', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-002', category: 'stir_fry',
    names: { zh: '越式炒麵', en: 'Vietnamese Stir-fried Noodle', ja: 'ベトナム風焼きそば', ko: '베트남식 볶음면' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🥢', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-003', category: 'stir_fry',
    names: { zh: '炒冬粉', en: 'Stir-fried Glass Noodle', ja: '炒め春雨', ko: '볶음 당면' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🥢', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-004', category: 'stir_fry',
    names: { zh: '越式炒空心麵', en: 'Vietnamese Stir-fried Macaroni', ja: 'ベトナム風炒めマカロニ', ko: '베트남식 볶음 마카로니' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🥢', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-005', category: 'stir_fry',
    names: { zh: '越式炒飯', en: 'Vietnamese Fried Rice', ja: 'ベトナム風チャーハン', ko: '베트남식 볶음밥' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍳', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-006', category: 'stir_fry',
    names: { zh: '炒青菜', en: 'Stir-fried Seasonal Vegetables', ja: '野菜炒め', ko: '채소 볶음' },
    price: [{ label: null, value: 60 }],
    image: null, emoji: '🥬', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-007', category: 'stir_fry',
    names: { zh: '咖喱炒飯', en: 'Saté Curry Fried Rice', ja: 'サテーカレーチャーハン', ko: '사테 카레 볶음밥' },
    price: [{ label: null, value: 90 }],
    image: null, emoji: '🍛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-008', category: 'stir_fry',
    names: { zh: '咖喱炒河粉', en: 'Saté Curry Stir-fried Rice Noodle', ja: 'サテーカレー炒めフォー', ko: '사테 카레 볶음 쌀국수' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🍛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-009', category: 'stir_fry',
    names: { zh: '咖喱炒麵（辣）', en: 'Saté Curry Stir-fried Noodle (Spicy)', ja: 'サテーカレー焼きそば（辛口）', ko: '사테 카레 볶음면 (매운맛)' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🍛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-010', category: 'stir_fry',
    names: { zh: '咖喱炒冬粉', en: 'Saté Curry Stir-fried Glass Noodle', ja: 'サテーカレー炒め春雨', ko: '사테 카레 볶음 당면' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🍛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'stir_fry-011', category: 'stir_fry',
    names: { zh: '咖喱炒空心麵', en: 'Saté Curry Stir-fried Macaroni', ja: 'サテーカレー炒めマカロニ', ko: '사테 카레 볶음 마카로니' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🍛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },

  // ════════════════════════════════════════════════════════
  //  乾類 DRY DISHES
  // ════════════════════════════════════════════════════════
  {
    id: 'dry-001', category: 'dry',
    names: { zh: '火腿皮絲飯', en: 'Vegetarian Ham & Shredded Tofu Rice', ja: '素ハムと肉でんぶご飯', ko: '채식 햄 & 채 두부 밥' },
    price: [{ label: null, value: 80 }],
    image: null, emoji: '🍱', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-002', category: 'dry',
    names: { zh: '乾皮絲米線', en: 'Dry Rice Noodle with Shredded Tofu', ja: '乾きビーフンと肉でんぶ', ko: '건식 채 두부 쌀국수' },
    price: [{ label: null, value: 80 }],
    image: null, emoji: '🍱', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-003', category: 'dry',
    names: { zh: '招牌麵包', en: 'Signature Baguette Sandwich', ja: '看板バインミー', ko: '시그니처 바게트 샌드위치' },
    price: [{ label: null, value: 80 }],
    image: null, emoji: '🥖', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-004', category: 'dry',
    names: { zh: '法國麵包卷（皮絲）', en: 'Baguette Roll with Shredded Tofu', ja: '肉でんぶのバインミー巻き', ko: '채 두부 바게트 롤' },
    price: [{ label: null, value: 80 }],
    image: null, emoji: '🥖', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-005', category: 'dry',
    names: { zh: '法國麵包（火腿）', en: 'Baguette with Vegetarian Ham', ja: '素ハムのバインミー', ko: '채식 햄 바게트' },
    price: [{ label: null, value: 80 }],
    image: null, emoji: '🥖', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-006', category: 'dry',
    names: { zh: '越式煎薄餅', en: 'Vietnamese Sizzling Crepe (Bánh Xèo)', ja: 'バインセオ（ベトナム風クレープ）', ko: '베트남 부침 크레이프 (반쎄오)' },
    price: [{ label: null, value: 100 }],
    image: null, emoji: '🥞', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-007', category: 'dry',
    names: { zh: '香春辣拉餅', en: 'Crispy Spring Roll Pastry', ja: 'サクサク春巻きペストリー', ko: '바삭한 스프링 롤 페이스트리' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🥙', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-008', category: 'dry',
    names: { zh: '原味素馨香', en: 'Original Vegetarian Patty', ja: 'オリジナル素肉パティ', ko: '오리지널 채식 패티' },
    price: [{ label: null, value: 70 }],
    image: null, emoji: '🌿', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-009', category: 'dry',
    names: { zh: '披薩', en: 'Vegetarian Pizza', ja: 'ベジタリアンピザ', ko: '채식 피자' },
    price: [{ label: null, value: 110 }],
    image: null, emoji: '🍕', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-010', category: 'dry',
    names: { zh: '鮮味春捲', en: 'Fresh Spring Rolls', ja: 'フレッシュ生春巻き', ko: '신선한 스프링 롤' },
    price: [{ label: null, value: 70 }],
    image: null, emoji: '🫔', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-011', category: 'dry',
    names: { zh: '木瓜絲', en: 'Green Papaya Salad', ja: 'グリーンパパイヤサラダ', ko: '그린 파파야 샐러드' },
    price: [{ label: null, value: 70 }],
    image: null, emoji: '🥗', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-012', category: 'dry',
    names: { zh: '白玉豆腐', en: 'Steamed Silken Tofu', ja: '蒸し絹ごし豆腐', ko: '찐 두부' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🫘', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-013', category: 'dry',
    names: { zh: '小菜', en: 'Side Dish', ja: 'おかず', ko: '반찬' },
    price: [{ label: null, value: 60 }],
    image: null, emoji: '🥗', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dry-014', category: 'dry',
    names: { zh: '燙青菜', en: 'Blanched Seasonal Greens', ja: '茹で青菜', ko: '데친 청채소' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '🥬', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },

  // ════════════════════════════════════════════════════════
  //  湯 SOUPS
  // ════════════════════════════════════════════════════════
  {
    id: 'soup-001', category: 'soup',
    names: { zh: '紫菜湯', en: 'Seaweed Soup', ja: '海苔スープ', ko: '미역 수프' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🥣', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'soup-002', category: 'soup',
    names: { zh: '豆腐湯', en: 'Tofu Soup', ja: '豆腐スープ', ko: '두부 수프' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🥣', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'soup-003', category: 'soup',
    names: { zh: '綜合湯', en: 'Mixed Vegetable Soup', ja: '具だくさんスープ', ko: '모둠 채소 수프' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🥣', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'soup-004', category: 'soup',
    names: { zh: '紅燒湯', en: 'Braised Vegetable Soup', ja: '醤油煮込みスープ', ko: '홍소 수프' },
    price: [{ label: null, value: 40 }],
    image: null, emoji: '🥣', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },

  // ════════════════════════════════════════════════════════
  //  飲料 DRINKS
  // ════════════════════════════════════════════════════════
  {
    id: 'drink-001', category: 'drink',
    names: { zh: '黑咖啡', en: 'Vietnamese Iced Black Coffee', ja: 'ベトナム風アイスコーヒー', ko: '베트남식 아이스 블랙 커피' },
    price: [{ label: null, value: 60 }],
    image: null, emoji: '☕', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-002', category: 'drink',
    names: { zh: '煉乳咖啡', en: 'Vietnamese Iced Condensed Milk Coffee', ja: 'ベトナム風練乳アイスコーヒー', ko: '베트남식 연유 아이스 커피' },
    price: [{ label: null, value: 60 }],
    image: null, emoji: '☕', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-003', category: 'drink',
    names: { zh: '冰檸檬汁', en: 'Iced Lemon Juice', ja: 'アイスレモンジュース', ko: '아이스 레몬 주스' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '🍋', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-004', category: 'drink',
    names: { zh: '冰蘿蔔子汁', en: 'Iced Tamarind Juice', ja: 'アイスタマリンドジュース', ko: '아이스 타마린드 주스' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '🧃', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-005', category: 'drink',
    names: { zh: '椰子水', en: 'Coconut Water', ja: 'ココナッツウォーター', ko: '코코넛 워터' },
    price: [{ label: null, value: 35 }],
    image: null, emoji: '🥥', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-006', category: 'drink',
    names: { zh: '豆奶', en: 'Soy Milk', ja: '豆乳', ko: '두유' },
    price: [{ label: null, value: 35 }],
    image: null, emoji: '🥛', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'drink-007', category: 'drink',
    names: { zh: '寧檸綠茶', en: 'Lemon Green Tea', ja: 'レモングリーンティー', ko: '레몬 그린 티' },
    price: [{ label: null, value: 35 }],
    image: null, emoji: '🍵', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },

  // ════════════════════════════════════════════════════════
  //  甜點 DESSERTS
  // ════════════════════════════════════════════════════════
  {
    id: 'dessert-001', category: 'dessert',
    names: { zh: '越南涼糕', en: 'Vietnamese Steamed Layer Cake (Bánh Da Lợn)', ja: 'ベトナム蒸し層ケーキ', ko: '베트남 층층 떡케이크' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '🍮', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dessert-002', category: 'dessert',
    names: { zh: '果凍', en: 'Agar Jelly', ja: '寒天ゼリー', ko: '한천 젤리' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '💚', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
  {
    id: 'dessert-003', category: 'dessert',
    names: { zh: '摩摩喳喳', en: 'Chè — Vietnamese Sweet Dessert Soup', ja: 'チェー（ベトナム風スイーツスープ）', ko: '쩨 (베트남식 달콤한 수프)' },
    price: [{ label: null, value: 50 }],
    image: null, emoji: '🍡', tags: [],
    desc:  { zh: '', en: '', ja: '', ko: '' },
    note:  { zh: '', en: '', ja: '', ko: '' },
  },
];
